import mary from '../../assets/images/mary.svg'

export const avatars = [
    {
        id: '1',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 120
    },
    {
        id: '2',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 203
    },
    {
        id: '3',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 106
    },
    {
        id: '4',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 215
    },
    {
        id: '5',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 567
    },
    {
        id: '6',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 567
    },
    {
        id: '7',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 146
    },
    {
        id: '8',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 345
    },
    {
        id: '9',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 567
    },
    {
        id: '10',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 215
    },
    {
        id: '11',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 800
    },
    {
        id: '12',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 906
    },
    {
        id: '13',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 260
    },
    {
        id: '14',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 307
    },
    {
        id: '15',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 111
    },
    {
        id: '16',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 737
    },
    {
        id: '17',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 127
    },
    {
        id: '18',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 678
    },
    {
        id: '19',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 345
    },
    {
        id: '20',
        username: 'Iyanaya',
        name: 'Demilade Oni',
        image: mary,
        contestantId: 12,
        sex: 'Male',
        state: 'Calabar',
        lifestyle: 'Artiste',
        favorites: 'Singing and Dancing',
        strenght: 'Vocals',
        weakness: 'Instruments',
        points: 215
    }
]